### ISSUE TITLE
Ambiguous naming?

### ISSUE THREAD

**Issue by thomaseizinger** [sam0x17/supertrait#1]
Hi!

I stumbled upon your crate via the Associated Type Default tracking issue, thanks for linking it! I was wondering whether or not you are aware that "supertrait" already has a meaning in the Rust world that might be confusing in regards to what your macro does: https://doc.rust-lang.org/rust-by-example/trait/supertraits.html

**Comment by sam0x17** [comment]
Yeah it's an intentional sort of back-reference. Traits created with this crate are often going to be actual supertraits themselves since that is a common scenario where default associated types are needed.
